name: Run Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: [3.2, 3.3, 3.4]
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: cat env.example env.development > .env
      - name: Load .env file
        uses: xom9ikk/dotenv@v2.3.0
      - name: Set up Ruby 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundle install
        run: bundle install
      - name: Run linter for Ruby
        run: bundle exec standardrb
      - name: Run tests
        run: bundle exec rspec
